# Generated by Django 5.1.1 on 2026-05-15 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_alter_cargo_actualizado_por_alter_cargo_creado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionCargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('tipo', models.CharField(choices=[('descomposicion', 'Descomposición'), ('combinacion', 'Combinación'), ('renovacion', 'Renovación')], max_length=20)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('cargos_destino', models.ManyToManyField(related_name='operaciones_como_destino', to='departamentos.cargo')),
                ('cargos_origen', models.ManyToManyField(related_name='operaciones_como_origen', to='departamentos.cargo')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamentos.resolucion')),
            ],
            options={
                'verbose_name': 'Operación de Cargo',
                'verbose_name_plural': 'Operaciones de Cargo',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('sigla', models.CharField(blank=True, help_text='Sigla corta (ADG, JTP, ADJ, ASO, TIT). Vacía para tipos sin puntaje.', max_length=10, null=True)),
                ('descripcion', models.CharField(help_text='Descripción tal como aparece en el sistema de origen (ej. PROFESOR TITULAR).', max_length=100)),
                ('dedicacion', models.CharField(choices=[('SIMP', 'Simple'), ('SEMI', 'Semi (Part-Time)'), ('EXCL', 'Exclusiva (Full-Time)'), ('35HS', '35 Horas')], max_length=10)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, help_text='Puntaje equivalente. Null si el tipo no participa en combinatoria.', max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Tipo de Cargo',
                'verbose_name_plural': 'Tipos de Cargo',
                'ordering': ['descripcion', 'dedicacion'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='tipo_cargo',
            field=models.ForeignKey(blank=True, help_text='Tipo de cargo (incluye dedicación). Null si aún no se asignó.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='departamentos.tipocargo'),
        ),
        migrations.AddConstraint(
            model_name='tipocargo',
            constraint=models.UniqueConstraint(fields=('descripcion', 'dedicacion'), name='unique_tipocargo_descripcion_dedicacion'),
        ),
    ]
