# Generated by Django 5.1.1 on 2026-05-15 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0008_seed_tipocargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargohistorial',
            name='no_docente',
            field=models.ForeignKey(blank=True, help_text='Ocupante no-docente. Mutuamente exclusivo con docente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_cargos', to='departamentos.nodocente'),
        ),
        migrations.AlterField(
            model_name='cargohistorial',
            name='docente',
            field=models.ForeignKey(blank=True, help_text='Ocupante docente. Mutuamente exclusivo con no_docente.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departamentos.docente'),
        ),
    ]
