# Generated by Django 5.1.1 on 2026-05-15 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0009_cargohistorial_no_docente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='asignatura',
            field=models.ForeignKey(blank=True, help_text='Asignatura vinculada (solo para cargos docentes). Opcional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='departamentos.asignatura'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='Departamento que gestiona el cargo. Null mientras está sin vincular.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='departamentos.departamento'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='resolucion_oficializacion',
            field=models.ForeignKey(blank=True, help_text='Resolución que oficializa la creación / asignación del cargo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_oficializados', to='departamentos.resolucion'),
        ),
    ]
