# Generated by Django 5.1.1 on 2026-05-26 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0010_cargo_departamento_asignatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignaturadocente',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='cargo',
            name='departamento',
        ),
        migrations.CreateModel(
            name='CargoDepartamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('descripcion', models.CharField(blank=True, help_text='Nombre interno del slot (ej. "Auxiliar de Análisis II").', max_length=200)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('asignatura', models.ForeignKey(blank=True, help_text='Asignatura vinculada (opcional). Debe pertenecer al mismo departamento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos_departamento', to='departamentos.asignatura')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(help_text='Departamento dueño del slot.', on_delete=django.db.models.deletion.PROTECT, related_name='cargos_departamento', to='departamentos.departamento')),
                ('tipo_cargo', models.ForeignKey(blank=True, help_text='Tipo de cargo deseado para el slot (PROFESOR TITULAR/SIMP, etc.).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos_departamento', to='departamentos.tipocargo')),
            ],
            options={
                'verbose_name': 'Cargo de Departamento',
                'verbose_name_plural': 'Cargos de Departamento',
                'ordering': ['departamento', 'descripcion'],
            },
        ),
        migrations.AddField(
            model_name='asignaturadocente',
            name='cargo_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to='departamentos.cargodepartamento'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='cargo_departamento',
            field=models.OneToOneField(blank=True, help_text='Slot de departamento al que está vinculado este cargo (plata). 1:1.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo', to='departamentos.cargodepartamento'),
        ),
    ]
