# Generated by Django 5.1.1 on 2026-08-26 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0012_historial_y_operaciones_a_cargodepartamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='codigo_siu',
            field=models.CharField(blank=True, help_text='Código en SIU Guaraní (ej. 15_E10). Clave de cruce con el sistema académico.', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='conciliada_siu',
            field=models.BooleanField(default=False, help_text='True si el nombre coincide con el de SIU Guaraní y no requiere revisión.'),
        ),
        migrations.AddField(
            model_name='persona',
            name='acoop',
            field=models.BooleanField(default=False, verbose_name='Aporta a ACOOP'),
        ),
        migrations.AddField(
            model_name='persona',
            name='cuil',
            field=models.CharField(blank=True, help_text='CUIL sin guiones. Es la clave de cruce con liquidaciones y SIU.', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='estado_agente',
            field=models.CharField(choices=[('activo', 'Activo'), ('licencia', 'En licencia'), ('jubilado', 'Jubilado'), ('renuncia', 'Renunció'), ('inactivo', 'Inactivo')], default='activo', help_text='Situación de revista del agente (distinto de `estado`, que es el borrado lógico).', max_length=10),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha de ingreso a la Universidad, para calcular antigüedad.', null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro / No informa')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='tipocargo',
            name='codigo',
            field=models.PositiveIntegerField(blank=True, help_text='Código oficial UNT del cargo (705, 706, 709, 716, 740…). Es la clave de cruce con designaciones, liquidación y SIU.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tipocargo',
            name='horas_semanales',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Carga horaria semanal del cargo (40 exclusiva, 20 semi, 10 simple).', null=True),
        ),
        migrations.AddField(
            model_name='tipocargo',
            name='rango',
            field=models.CharField(blank=True, choices=[('TITULAR', 'Titular'), ('ASOCIADO', 'Asociado'), ('ADJUNTO', 'Adjunto'), ('JTP', 'JTP'), ('ADG', 'Auxiliar Docente de Primera'), ('AUX2', 'Auxiliar Docente de Segunda'), ('GESTION', 'Cargo de gestión'), ('NODOCENTE', 'No docente')], help_text='Rango normalizado, usado para agrupar en el reporte de planta.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cargodepartamento',
            name='departamento',
            field=models.ForeignKey(help_text='Departamento dueño del cargo.', on_delete=django.db.models.deletion.PROTECT, related_name='cargos_departamento', to='departamentos.departamento'),
        ),
        migrations.AlterField(
            model_name='cargodepartamento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Nombre interno del cargo (ej. "Auxiliar de Análisis II").', max_length=200),
        ),
        migrations.AlterField(
            model_name='cargodepartamento',
            name='tipo_cargo',
            field=models.ForeignKey(blank=True, help_text='Tipo de cargo (PROFESOR TITULAR/SIMP, etc.).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargos_departamento', to='departamentos.tipocargo'),
        ),
        migrations.CreateModel(
            name='AsignacionFuncion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('descripcion', models.CharField(help_text='Función asignada, ej. "Laboratorio de Telecomunicaciones".', max_length=200)),
                ('expediente', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_funcion', to='departamentos.area')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_funcion', to='departamentos.departamento')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='departamentos.docente')),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_funcion', to='departamentos.resolucion')),
            ],
            options={
                'verbose_name': 'Asignación de Función',
                'verbose_name_plural': 'Asignaciones de Funciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Designacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('tipo', models.CharField(choices=[('CON', 'Concurso'), ('CON_INTERINO', 'Concurso interino'), ('DI_GENUINO', 'Designación interina genuina'), ('DI_NO_GENUINO', 'Designación interina no genuina'), ('EA_POSITIVA', 'Evaluación académica positiva'), ('EA_NEGATIVA', 'Evaluación académica negativa'), ('PRORROGA_DI_GENUINO', 'Prórroga de DI genuina'), ('PRORROGA_DI_NO_GENUINO', 'Prórroga de DI no genuina'), ('PROR_70_ANIOS', 'Prórroga 70 años'), ('PROR_CARGO_GESTION', 'Prórroga por cargo de gestión'), ('RENUNCIA', 'Renuncia'), ('REINTEGRO', 'Reintegro'), ('ALTA', 'Alta de cargo'), ('BAJA', 'Baja de cargo')], max_length=25)),
                ('codigo_cargo', models.PositiveIntegerField(blank=True, help_text='Código UNT del cargo (705, 716…). Se autocompleta desde tipo_cargo. Es la clave por la que se agrupan las designaciones en una ocupación.', null=True)),
                ('tipo_instrumento', models.CharField(blank=True, choices=[('Res_Rec', 'Resolución Rectoral'), ('Res_Dec', 'Resolución Decanal'), ('Res_CD', 'Resolución de Consejo Directivo'), ('DGPRES', 'Disposición DGPRES'), ('Expte', 'Sólo expediente'), ('Sin_instrumento', 'Sin instrumento')], max_length=20, null=True)),
                ('expediente', models.CharField(blank=True, help_text='Nº de expediente, ej. "3229/2024".', max_length=100, null=True)),
                ('nro_resolucion', models.CharField(blank=True, help_text='Nº de resolución cuando todavía no se cargó la Resolución completa.', max_length=100, null=True)),
                ('dgpres', models.CharField(blank=True, help_text='Disposición presupuestaria que habilita el gasto, ej. "DGPRES 1374/2024".', max_length=100, null=True)),
                ('fecha_desde', models.DateField(blank=True, null=True)),
                ('fecha_hasta', models.DateField(blank=True, help_text='Vencimiento explícito. Si está vacío se estima según el tipo de trámite.', null=True)),
                ('en_tramite', models.BooleanField(default=False, help_text='La designación está iniciada pero sin instrumento firme.')),
                ('renuncia_definitiva', models.BooleanField(default=False, help_text='Sólo para RENUNCIA: distingue la renuncia definitiva de la condicionada.')),
                ('rol_gestion', models.CharField(blank=True, help_text='Cargo de gestión que motiva la prórroga (Decano, Secretario…).', max_length=100, null=True)),
                ('texto_original', models.TextField(blank=True, help_text='Texto tal como venía en la planilla, para trazabilidad de la migración.', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designaciones', to='departamentos.area')),
                ('asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designaciones', to='departamentos.asignatura')),
                ('cargo_departamento', models.ForeignKey(blank=True, help_text='Cargo de departamento afectado (opcional mientras no esté vinculado).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designaciones', to='departamentos.cargodepartamento')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designaciones', to='departamentos.docente')),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designaciones', to='departamentos.resolucion')),
                ('tipo_cargo', models.ForeignKey(blank=True, help_text='Tipo de cargo designado. Define rango, dedicación y horas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designaciones', to='departamentos.tipocargo')),
            ],
            options={
                'verbose_name': 'Designación',
                'verbose_name_plural': 'Designaciones',
                'ordering': ['-fecha_desde', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaAsignatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('anio', models.PositiveSmallIntegerField()),
                ('inscriptos', models.PositiveIntegerField(default=0)),
                ('aprobados', models.PositiveIntegerField(default=0)),
                ('promovidos', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='departamentos.asignatura')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='departamentos.carrera')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Estadística de Asignatura',
                'verbose_name_plural': 'Estadísticas de Asignaturas',
                'ordering': ['-anio', 'asignatura'],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('tipo', models.CharField(choices=[('sin_goce', 'Sin goce de sueldo'), ('con_goce', 'Con goce de sueldo'), ('cargo_mayor_jerarquia', 'Por cargo de mayor jerarquía'), ('maternidad', 'Maternidad / paternidad'), ('enfermedad', 'Enfermedad de largo tratamiento'), ('estudio', 'Beca / estudio'), ('otra', 'Otra')], max_length=25)),
                ('codigo_cargo', models.PositiveIntegerField(blank=True, help_text='Código UNT del cargo sobre el que se toma la licencia.', null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacío = licencia vigente sin fecha de reintegro.', null=True)),
                ('expediente', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('cargo_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias', to='departamentos.cargodepartamento')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to='departamentos.docente')),
                ('reemplazante', models.ForeignKey(blank=True, help_text='Docente que cubre el cargo durante la licencia, si lo hay.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazos', to='departamentos.docente')),
                ('resolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias', to='departamentos.resolucion')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['-fecha_inicio', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('tipo', models.CharField(choices=[('ea_iniciar', 'Iniciar evaluación académica'), ('regularizar_cargo', 'Regularizar cargo'), ('cobro_sueldo', 'Revisar cobro de sueldo'), ('di_no_genuina', 'Designación interina no genuina'), ('renovacion', 'Renovación pendiente'), ('concurso', 'Llamado a concurso'), ('jubilacion', 'Trámite jubilatorio'), ('licencia', 'Licencia'), ('otro', 'Otro')], default='otro', max_length=25)),
                ('descripcion', models.TextField(help_text='Qué hay que hacer, ej. "revisar cobro de sueldo".')),
                ('fecha_novedad', models.DateField(help_text='Fecha de la novedad que dispara el seguimiento.')),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, help_text='Área u oficina responsable, ej. "Depto Personal".', max_length=120, null=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estado_seguimiento', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('resuelto', 'Resuelto'), ('descartado', 'Descartado')], default='pendiente', max_length=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('actualizado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('designacion', models.ForeignKey(blank=True, help_text='Designación a la que se refiere la novedad, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos', to='departamentos.designacion')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='departamentos.docente')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha_novedad', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='designacion',
            index=models.Index(fields=['docente', 'codigo_cargo'], name='departament_docente_67d32d_idx'),
        ),
        migrations.AddIndex(
            model_name='designacion',
            index=models.Index(fields=['tipo'], name='departament_tipo_32edeb_idx'),
        ),
        migrations.AddIndex(
            model_name='designacion',
            index=models.Index(fields=['fecha_desde'], name='departament_fecha_d_eec30d_idx'),
        ),
        migrations.AddConstraint(
            model_name='estadisticaasignatura',
            constraint=models.UniqueConstraint(fields=('asignatura', 'carrera', 'anio'), name='unique_estadistica_asig_carrera_anio'),
        ),
        migrations.AddIndex(
            model_name='seguimiento',
            index=models.Index(fields=['docente', 'estado_seguimiento'], name='departament_docente_33336f_idx'),
        ),
    ]
