# Generated by Django 5.1.1 on 2026-05-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0010_cargo_departamento_asignatura'),
        ('usuarios', '0002_alter_user_legajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departamentos_administrados',
            field=models.ManyToManyField(blank=True, help_text='Departamentos cuyos cargos puede gestionar el usuario. Vacío = ve todos (típicamente para admins).', related_name='jefes_administradores', to='departamentos.departamento', verbose_name='Departamentos administrados'),
        ),
    ]
